services:
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      # - ./.env
    volumes:
      - db:/var/lib/postgresql/data
    # command: ["sh", "-c", "printenv && tail -f /dev/null"]

volumes:
  db:
    driver: local